apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: images
  namespace: {{.KUBE_NAMESPACE}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: images
        env: {{.KUBE_NAMESPACE}}
    spec:
      containers:
      - name: images
        image: "{{.IMAGE_TAG}}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "0.05Gi"
            cpu: "0.008"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 60
          httpGet:
            port: 80
            path: /
      imagePullSecrets:
      - name: images-registry-deploy-token
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0